site_name: Code Historian Documentation
site_description: Documentation for the Code Historian project
repo_url: https://github.com/abcdqfr/code-historian
repo_name: code-historian

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo

plugins:
  - search
  - mermaid
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Basic Usage: user-guide/basic-usage.md
    - Advanced Features: user-guide/advanced-features.md
    - Best Practices: user-guide/best-practices.md
  - Development:
    - Architecture: development/architecture.md
    - Contributing: development/contributing.md
    - Plugin Development: development/plugin-development.md
  - Project Status:
    - Progress Report: status/progress-report.md
    - Test Coverage: status/test-coverage.md
    - Performance Metrics: status/performance-metrics.md
  - Reference:
    - API Documentation: reference/api-docs.md
    - Configuration Reference: reference/config-reference.md
    - CLI Reference: reference/cli-reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/abcdqfr/code-historian
  generator: false 